import Layout from '@/layouts/LayoutPublic';
import { Box } from '@mantine/core';
import Head from 'next/head';
import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';

export default function SpecPage() {
  return (
    <>
      <Head>
        <title>SwaggerUI</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        <style>
          {`
          .swagger-ui input[type=email], .swagger-ui input[type=file], .swagger-ui input[type=password], .swagger-ui input[type=search], .swagger-ui input[type=text], .swagger-ui textarea {
            color: black !important;
          }
        `}
        </style>
      </Head>
      <Box
        style={{
          backgroundColor: 'white'
        }}
        py={1}
      >
        <main>
          <SwaggerUI url={`/api/consumer/v2/swagger.json`} />
        </main>
      </Box>
    </>
  );
}
SpecPage.getLayout = (page: any) => <Layout>{page}</Layout>;
